2020-10-10 00:19:10,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 563834ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 00:29:16,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564874ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 00:39:21,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564449ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 00:49:27,001 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 565014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 00:59:31,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 563591ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 01:09:36,001 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564989ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 01:19:42,001 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 565993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 01:29:47,003 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564993ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 01:39:53,001 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 565991ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 01:49:58,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564815ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:00:03,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564990ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:10:09,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566000ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:20:14,002 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 564997ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:29:47,001 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 532987ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:39:26,646 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 579492ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:49:36,222 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 569429ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 02:59:43,184 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566845ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 03:09:50,158 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566853ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 03:19:59,135 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568849ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 03:30:06,158 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566879ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 03:40:15,186 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568769ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 03:50:22,157 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566716ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:00:29,158 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566833ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:10:36,190 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:20:44,142 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567592ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:30:51,274 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566799ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:41:00,127 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568698ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 04:51:07,238 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566833ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:01:15,206 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:11:22,134 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566817ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:21:30,137 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:31:37,129 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566870ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:41:44,185 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566845ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 05:51:51,146 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566831ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:01:59,137 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567844ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:12:06,207 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566527ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:22:14,118 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:32:21,145 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:42:29,126 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567861ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 06:52:36,177 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566889ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:02:45,143 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568797ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:12:53,178 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:23:00,156 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566750ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:33:09,178 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568808ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:43:17,178 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 07:53:14,128 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 576810ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 08:03:22,138 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567811ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 08:13:30,119 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567765ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 08:23:39,184 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 568777ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 08:33:46,150 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 566705ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 08:43:54,132 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 567667ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 09:48:50,357 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 3855743ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 10:00:58,761 ERROR 22463 [-/192.168.7.50/-/27ms POST /gannt/created] nodejs.Error: WHERE parameter "id" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2258:13)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2245:35)
    at MySQLQueryGenerator.getWhereConditions (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2663:19)
    at MySQLQueryGenerator.selectQuery (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1316:28)
    at MySQLQueryInterface.select (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-interface.js:939:27)
    at Function.findAll (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:1753:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Function.Gannt.findById (/Users/lxd/Desktop/mine/egg-example/app/model/gannt.js:30:12)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 22463
hostname: localhost

2020-10-10 10:16:16,131 ERROR 23243 [-/192.168.7.50/-/2ms POST /gannt/created] nodejs.ReferenceError: res is not defined
    at GanntController.created (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:100:24)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:45:18)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 23243
hostname: localhost

2020-10-10 10:19:03,528 ERROR 23243 [-/192.168.7.50/-/0ms POST /gannt/created] nodejs.ReferenceError: res is not defined
    at GanntController.created (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:100:24)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:45:18)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 23243
hostname: localhost

2020-10-10 10:20:14,723 ERROR 23397 [-/192.168.7.50/-/10ms POST /gannt/created] nodejs.ReferenceError: Cannot access 'params' before initialization
    at GanntController.created (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:97:46)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at next (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:45:18)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:44:32)
    at /Users/lxd/Desktop/mine/egg-example/node_modules/koa-compose/index.js:36:12
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 23397
hostname: localhost

2020-10-10 10:54:59,320 ERROR 24747 [-/192.168.7.50/-/42ms GET /gannt/lists?currentPage=1&currentSizes=10&filters=] nodejs.SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '~* '^[len[i].id_]'' at line 1
    at Query.formatError (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.rawSelect (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-interface.js:980:18)
    at async Function.aggregate (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:1986:19)
    at async Function.count (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:2037:12)
    at async Promise.all (index 0)
    at async Function.findAndCountAll (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:2085:27)
    at async GanntController.lists (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:76:21)
name: "SequelizeDatabaseError"
parent: {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\x7e* '^[len[i].id_]'' at line 1","sql":"SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` \\x7e* '^[len[i].id_]';"}
original: {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\\x7e* '^[len[i].id_]'' at line 1","sql":"SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` \\x7e* '^[len[i].id_]';"}
sql: "SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` ~* '^[len[i].id_]';"
parameters: undefined
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 24747
hostname: localhost

2020-10-10 10:56:32,507 ERROR 24826 [-/192.168.7.50/-/25ms GET /gannt/lists?currentPage=1&currentSizes=10&filters=] nodejs.SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('1_')' at line 1
    at Query.formatError (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:239:16)
    at Query.run (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/mysql/query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.rawSelect (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/dialects/abstract/query-interface.js:980:18)
    at async Function.aggregate (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:1986:19)
    at async Function.count (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:2037:12)
    at async Promise.all (index 0)
    at async Function.findAndCountAll (/Users/lxd/Desktop/mine/egg-example/node_modules/sequelize/lib/model.js:2085:27)
    at async GanntController.lists (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:76:21)
name: "SequelizeDatabaseError"
parent: {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('1_')' at line 1","sql":"SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` LIKE ANY ('1_');"}
original: {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('1_')' at line 1","sql":"SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` LIKE ANY ('1_');"}
sql: "SELECT count(*) AS `count` FROM `gannt` AS `gannt` WHERE `gannt`.`childId` LIKE ANY ('1_');"
parameters: undefined
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 24826
hostname: localhost

2020-10-10 13:36:42,003 ERROR 19253 nodejs.ClusterClientNoResponseError: client no response in 5566438ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lxd/Desktop/mine/egg-example/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
name: "ClusterClientNoResponseError"
pid: 19253
hostname: bogon

2020-10-10 14:31:12,694 ERROR 28889 [-/192.168.7.50/-/30ms GET /gannt/lists?currentPage=1&currentSizes=10&filters=] nodejs.ReferenceError: _ is not defined
    at GanntController.lists (/Users/lxd/Desktop/mine/egg-example/app/controller/gannt.js:78:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/lxd/Desktop/mine/egg-example/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/lxd/Desktop/mine/egg-example/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/lxd/Desktop/mine/egg-example/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/lxd/Desktop/mine/egg-example/node_modules/koa-static-cache/index.js:41:56
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 28889
hostname: lxddeMacBook-Pro.local

